apiVersion: 1

contactPoints:
  - orgId: 1
    name: Email Alerts
    receivers:
      - uid: email_alerts
        type: email
        settings:
          addresses: farmer@YOUR_WEBSITE
        disableResolveMessage: false
  - orgId: 1
    name: No Notifications
    receivers: []
